#Base Image
FROM python:3.6.5-alpine

#Install Dependencies
RUN apk update && \
	apk add --virtual build-deps gcc python-dev musl-dev && \
	apk add postgresql-dev && \
	apk add netcat-openbsd

#Set Working Directory
WORKDIR /usr/src/app

#Add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

#Add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

#Add app
COPY . /usr/src/app

#Run Server
CMD ["sh", "/usr/src/app/entrypoint.sh"]